@startuml 100_addLinksToStaticList
skinparam responseMessageBelowArrow true

title
RequestForAddingLinksToStaticListCausesFileUpdate
end title

participant "external" as requestor
participant "AIPS://v1/add-links-to-static-list" as addLinks

note over addLinks
  write new link-IDs to file 
  (without automations);
  no changes to already existing 
  entries
end note
requestor -> addLinks: {linkIdList}
activate addLinks
addLinks --> requestor

deactivate addLinks

@enduml