@startuml 106_listLinks
skinparam responseMessageBelowArrow true

title
RequestForListingLinksInStaticListCausesFileReading
end title

participant "external" as requestor
participant "AIPS://v1/list-links" as listLinks

requestor -> listLinks: <i>optional:</i> {linkIdList}
activate listLinks

note over listLinks
  - if requestor provided linkIdList filter the data 
    from the file for those linkIds included in the
    linkIdList,
  - else return complete staticList
end note
listLinks --> requestor: {list-of-(linkId, automationNamesList)}

deactivate listLinks

@enduml