@startuml 400_addLinksToPowerSavingActivationQueue
skinparam responseMessageBelowArrow true

title
RequestForAddingLinksToPowerSavingActivationQueueCausesActivationQueueUpdate
end title

participant "external" as requestor
participant "AIPS://v1/add-links-to-power-saving-activation-queue" as addLinks
participant "ElasticSearch" as es

requestor -> addLinks: {linkIdList, automationName, switchingOperationName}
activate addLinks

addLinks -> es:  {linkIdList, automationName, switchingOperationName}

deactivate addLinks


footer

  Only queue update; cyclic operation on queue elements in own diagram
end footer


@enduml