@startuml 402_purgePowerSavingDeactivationQueue
skinparam responseMessageBelowArrow true

title
RequestForPurgingPowerSavingDeactivationQueueCausesDeactivationQueuePurge
end title

participant "external" as requestor
participant "AIPS://v1/purge-power-saving-deactivation-queue" as purgeQueue
participant "ElasticSearch" as es

requestor -> purgeQueue
activate purgeQueue

purgeQueue -> es

deactivate purgeQueue

@enduml